[build]
	publish = "dist"
	environment = {NODE_ENV = "production", API_URL = "https://zero-labs.netlify.app"}
	command = "npm run generate"
    functions = "./api"

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200
